import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <Toaster richColors position="bottom-center" />
            <body className={inter.className}>
                <header className="container bg-black/90 py-4 my-6 rounded-full text-white flex justify-between items-center shadow-lg drop-shadow-lg">
                    <Link href="/">
                        <h3 className="text-2xl">🏥 Patient Management</h3>
                    </Link>
                    <nav className="space-x-6">
                        <span>
                            <Link href="/user/add">Add User</Link>
                        </span>
                        <span>
                            <Link href="/user/update">Update User</Link>
                        </span>
                        <span>
                            <Link href="/user/certificate">
                                Download Certificate
                            </Link>
                        </span>
                    </nav>
                </header>
                {children}
            </body>
        </html>
    );
}
